"""Generate the compact Unicode tables used by tok_nfc.h.

The implementation needs canonical decomposition, canonical combining classes,
and non-Hangul composition pairs.  Hangul is handled algorithmically in C.
"""

import unicodedata


def canonical_decompositions():
    result = []
    for cp in range(0x110000):
        raw = unicodedata.decomposition(chr(cp))
        if not raw or raw.startswith("<"):
            continue
        seq = [int(item, 16) for item in raw.split()]
        if len(seq) > 2:
            raise RuntimeError(f"unexpected direct canonical decomposition: U+{cp:04X} {seq}")
        result.append((cp, seq + [0] * (2 - len(seq))))
    return result


def combining_ranges():
    result = []
    start = previous = value = None
    for cp in range(0x110000):
        current = unicodedata.combining(chr(cp))
        if current == 0:
            if start is not None:
                result.append((start, previous, value))
                start = previous = value = None
            continue
        if start is not None and cp == previous + 1 and current == value:
            previous = cp
        else:
            if start is not None:
                result.append((start, previous, value))
            start = previous = cp
            value = current
    if start is not None:
        result.append((start, previous, value))
    return result


def compositions(decompositions):
    result = []
    for cp, seq in decompositions:
        if not seq[1]:
            continue
        pair = chr(seq[0]) + chr(seq[1])
        if unicodedata.normalize("NFC", pair) == chr(cp):
            result.append((seq[0], seq[1], cp))
    return sorted(result)


decomp = canonical_decompositions()
ccc = combining_ranges()
compose = compositions(decomp)

print("/* GENERATED by tools/gen_nfc.py — do not edit by hand. */")
print("#ifndef TOK_NFC_H\n#define TOK_NFC_H\n#include <stdint.h>\n#include <stdlib.h>\n")
print("typedef struct { uint32_t cp, a, b; } nfc_decomp;")
print("static const nfc_decomp nfc_decomp_table[] = {")
for cp, seq in decomp:
    print(f"    {{0x{cp:X},0x{seq[0]:X},0x{seq[1]:X}}},")
print("};")
print(f"static const int nfc_decomp_count={len(decomp)};\n")

print("typedef struct { uint32_t lo, hi; uint8_t ccc; } nfc_ccc_range;")
print("static const nfc_ccc_range nfc_ccc_table[] = {")
for lo, hi, value in ccc:
    print(f"    {{0x{lo:X},0x{hi:X},{value}}},")
print("};")
print(f"static const int nfc_ccc_count={len(ccc)};\n")

print("typedef struct { uint32_t a, b, cp; } nfc_comp;")
print("static const nfc_comp nfc_comp_table[] = {")
for a, b, cp in compose:
    print(f"    {{0x{a:X},0x{b:X},0x{cp:X}}},")
print("};")
print(f"static const int nfc_comp_count={len(compose)};\n")

print(r'''
static int nfc_u8_next(const unsigned char *s,int len,int i,uint32_t *cp){
    unsigned char c=s[i];
    if(c<0x80){*cp=c;return 1;}
    if((c>>5)==0x6&&i+1<len){*cp=((c&31)<<6)|(s[i+1]&63);return 2;}
    if((c>>4)==0xE&&i+2<len){*cp=((c&15)<<12)|((s[i+1]&63)<<6)|(s[i+2]&63);return 3;}
    if((c>>3)==0x1E&&i+3<len){*cp=((c&7)<<18)|((s[i+1]&63)<<12)|((s[i+2]&63)<<6)|(s[i+3]&63);return 4;}
    *cp=0xFFFD;return 1;
}
static int nfc_u8_put(char *o,uint32_t cp){
    if(cp<0x80){o[0]=(char)cp;return 1;}
    if(cp<0x800){o[0]=(char)(0xC0|(cp>>6));o[1]=(char)(0x80|(cp&63));return 2;}
    if(cp<0x10000){o[0]=(char)(0xE0|(cp>>12));o[1]=(char)(0x80|((cp>>6)&63));o[2]=(char)(0x80|(cp&63));return 3;}
    o[0]=(char)(0xF0|(cp>>18));o[1]=(char)(0x80|((cp>>12)&63));o[2]=(char)(0x80|((cp>>6)&63));o[3]=(char)(0x80|(cp&63));return 4;
}
static const nfc_decomp *nfc_find_decomp(uint32_t cp){
    int lo=0,hi=nfc_decomp_count-1;
    while(lo<=hi){int m=(lo+hi)>>1;uint32_t v=nfc_decomp_table[m].cp;
        if(cp<v)hi=m-1;else if(cp>v)lo=m+1;else return &nfc_decomp_table[m];}
    return NULL;
}
static int nfc_ccc(uint32_t cp){
    int lo=0,hi=nfc_ccc_count-1;
    while(lo<=hi){int m=(lo+hi)>>1;
        if(cp<nfc_ccc_table[m].lo)hi=m-1;else if(cp>nfc_ccc_table[m].hi)lo=m+1;else return nfc_ccc_table[m].ccc;}
    return 0;
}
static uint32_t nfc_compose_pair(uint32_t a,uint32_t b){
    enum { SBASE=0xAC00,LBASE=0x1100,VBASE=0x1161,TBASE=0x11A7,LCOUNT=19,VCOUNT=21,TCOUNT=28,NCOUNT=588,SCOUNT=11172 };
    if(a>=LBASE&&a<LBASE+LCOUNT&&b>=VBASE&&b<VBASE+VCOUNT)
        return SBASE+(a-LBASE)*NCOUNT+(b-VBASE)*TCOUNT;
    if(a>=SBASE&&a<SBASE+SCOUNT&&(a-SBASE)%TCOUNT==0&&b>TBASE&&b<TBASE+TCOUNT)
        return a+(b-TBASE);
    int lo=0,hi=nfc_comp_count-1;
    while(lo<=hi){int m=(lo+hi)>>1;const nfc_comp *e=&nfc_comp_table[m];
        if(a<e->a||(a==e->a&&b<e->b))hi=m-1;else if(a>e->a||(a==e->a&&b>e->b))lo=m+1;else return e->cp;}
    return 0;
}
static void nfc_push(uint32_t **out,int *n,int *cap,uint32_t cp){
    enum { SBASE=0xAC00,LBASE=0x1100,VBASE=0x1161,TBASE=0x11A7,VCOUNT=21,TCOUNT=28,NCOUNT=588,SCOUNT=11172 };
    if(cp>=SBASE&&cp<SBASE+SCOUNT){
        int s=(int)(cp-SBASE);nfc_push(out,n,cap,LBASE+s/NCOUNT);nfc_push(out,n,cap,VBASE+(s%NCOUNT)/TCOUNT);
        if(s%TCOUNT)nfc_push(out,n,cap,TBASE+s%TCOUNT);return;
    }
    const nfc_decomp *d=nfc_find_decomp(cp);
    if(d){nfc_push(out,n,cap,d->a);if(d->b)nfc_push(out,n,cap,d->b);return;}
    if(*n==*cap){*cap*=2;*out=(uint32_t*)realloc(*out,(size_t)*cap*sizeof(uint32_t));}
    (*out)[(*n)++]=cp;
}
/* Returns a newly allocated NFC string. */
static char *tok_nfc_normalize(const char *text,int len,int *out_len){
    int cap=len>0?len:8,n=0;uint32_t *cp=(uint32_t*)malloc((size_t)cap*sizeof(uint32_t));
    for(int i=0;i<len;){uint32_t c;int k=nfc_u8_next((const unsigned char*)text,len,i,&c);i+=k;nfc_push(&cp,&n,&cap,c);}
    for(int i=1;i<n;i++){int cc=nfc_ccc(cp[i]);if(!cc)continue;uint32_t v=cp[i];int j=i;
        while(j>0){int prev=nfc_ccc(cp[j-1]);if(!prev||prev<=cc)break;cp[j]=cp[j-1];j--;}cp[j]=v;}
    int outn=0,starter_pos=-1,last_cc=0;
    for(int i=0;i<n;i++){uint32_t c=cp[i];int cc=nfc_ccc(c);uint32_t composed=0;
        if(starter_pos>=0&&(last_cc<cc||last_cc==0))composed=nfc_compose_pair(cp[starter_pos],c);
        if(composed){cp[starter_pos]=composed;}
        else{cp[outn]=c;if(cc==0)starter_pos=outn;last_cc=cc;outn++;}}
    char *out=(char*)malloc((size_t)outn*4+1);int bytes=0;
    for(int i=0;i<outn;i++)bytes+=nfc_u8_put(out+bytes,cp[i]);out[bytes]=0;free(cp);*out_len=bytes;return out;
}
#endif
''')
