#!/usr/bin/env python3
"""Emit DeepSeek punctuation/symbol ranges using pinned Unicode 15.0 data."""
import unicodedata

if unicodedata.unidata_version != '15.0.0':
    raise SystemExit('Regenerate with Python using Unicode 15.0.0')
ranges = []
for cp in range(0x110000):
    if unicodedata.category(chr(cp))[0] in ('P', 'S'):
        if ranges and cp == ranges[-1][1] + 1:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp])
print('/* Generated by tools/gen_deepseek_v4_unicode.py; Unicode 15.0.0. */')
print('#ifndef DEEPSEEK_V4_UNICODE_H\n#define DEEPSEEK_V4_UNICODE_H')
print('static const uint32_t dsv4_punctuation_symbols[][2] = {')
for i in range(0, len(ranges), 6):
    print('    ' + ''.join('{0x%X,0x%X},' % tuple(pair) for pair in ranges[i:i+6]))
print('};')
print('static int dsv4_is_punctuation_symbol(uint32_t cp) {')
print('    return uni_in(dsv4_punctuation_symbols, sizeof(dsv4_punctuation_symbols) / sizeof(dsv4_punctuation_symbols[0]), cp);\n}\n#endif')
